name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew :app2:assembleDebug

      - name: Verify generated APK path
        run: ls -R app2/build/outputs/apk/debug/

      - name: Upload Debug APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app2-debug
          path: app2/build/outputs/apk/debug/app2-debug.apk

  firebase-test-lab:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: app2-debug

      - name: Display structure of downloaded files
        run: ls -R

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_FIREBASE_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Run tests in Firebase Test Lab
        run: gcloud firebase test android run --app app2-debug.apk --type robo --device model=MediumPhone.arm,version=30,locale=en,orientation=portrait
